#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Load Composer Autoloader
if (file_exists($composer = __DIR__.'/vendor/autoload.php')) {
    require $composer;
}

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
